TebLocalPlannerROS:
  # Debugging (Aus, damit wir Warnungen sehen)
  optimization_verbose: false
  
  # Tolerances
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.01
  
  # Obstacles (sicherer Abstand)
  min_obstacle_dist: 0.20
  inflation_dist: 0.2
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  
  # Kinematics
  max_vel_x: 0.4
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.5
  acc_lim_x: 0.4
  acc_lim_theta: 0.5
  
  # Recovery
  oscillation_recovery: true   # Wieder an, sonst bleibt er hängen
  
  # Planning
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 2
